dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.3.2
  - smartcontractkit/chainlink-brownie-contracts@1.0.0
compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.3.2"
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@1.0.0"

dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}
